name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: copy to Deploy server 
        run: |
         scp -i ubuntu@52.0.176.0: /home/ubuntu/my-app 

      - name: Start Application
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@52.0.176.0 'pm2 restart server'
     
       
