name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: copy to Deploy server 
        run: |
         scp -r /home/ubuntu/demo_nodchat/* /home/ubuntu/node-app
      - name: Start Application
        run: |
         ssh -o StrictHostKeyChecking=no ubuntu@3.84.8.202 'pm2 restart api'
